const NOTIFICATION_TYPES = {
  FRIEND_REQUEST_SENT: "FRIEND_REQUEST_SENT",
  FRIEND_REQUEST_ACCEPTED: "FRIEND_REQUEST_ACCEPTED",
  FRIEND_BLOCKED : "FRIEND_BLOCKED",
  FRIEND_UNBLOCK : "FRIEND_UNBLOCKED"
};

module.exports = NOTIFICATION_TYPES;
